{% set name = "minikube" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 93a1060a6f73fcd3a568880405569932a07b0e781dae34c006bc0259b082bc5d

build:
  number: 1

requirements:
  build:
    - {{ compiler("go") }}
    - make
    - posix  # [win]
  run:
    - kubernetes

test:
  commands:
    - minikube version

about:
  home: http://github.com/kubernetes/minikube
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Run Kubernetes locally'
  description: |
    minikube implements a local Kubernetes cluster.
    minikube's primary goals are to be the best tool for local Kubernetes
    application development and to support all Kubernetes features that fit.
  doc_url: https://minikube.sigs.k8s.io/docs/
  dev_url: https://github.com/kubernetes/minikube

extra:
  recipe-maintainers:
    - xmnlab
    - esloch
