{% set name = "minikube" %}
{% set version = "1.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ffd1196bc9a5020be8a17920a69ec82ff68bb5e98903172b52d0c0d8533b7224

build:
  number: 0

requirements:
  build:
    - {{ compiler("go") }}
    - make
    - posix  # [win]
  run:
    - kubernetes

test:
  commands:
    - minikube version

about:
  home: http://github.com/kubernetes/minikube
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Run Kubernetes locally
  description: |
    minikube implements a local Kubernetes cluster.
    minikube's primary goals are to be the best tool for local Kubernetes
    application development and to support all Kubernetes features that fit.
  doc_url: https://minikube.sigs.k8s.io/docs/
  dev_url: https://github.com/kubernetes/minikube

extra:
  recipe-maintainers:
    - xmnlab
    - esloch
