context:
  name: minikube
  version: "1.38.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/kubernetes/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: f3401ff708235441d12ee47f5e8b5e7f55e7944585ae2a9bdb4b8cb629838f7c

build:
  number: 0

requirements:
  build:
    - if: linux and x86_64
      then:
        - ${{ compiler('go-cgo') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
      else:
        - ${{ compiler('go-nocgo') }}
    - go-licenses
    - make
    - if: win
      then:
        - git
        - posix
  run:
    - kubernetes

tests:
  - script:
      - minikube version

about:
  homepage: http://github.com/kubernetes/minikube
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Run Kubernetes locally
  description: |
    minikube implements a local Kubernetes cluster.
    minikube's primary goals are to be the best tool for local Kubernetes
    application development and to support all Kubernetes features that fit.
  documentation: https://minikube.sigs.k8s.io/docs/
  repository: https://github.com/kubernetes/minikube

extra:
  recipe-maintainers:
    - xmnlab
    - esloch
    - delsner
